version: '3.5'

services:
  mongo:
    image: mongo:3.4.20-xenial
    restart: always
    networks:
      - main
    ports:
      - "27017:27017"

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - main

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - main
    depends_on:
      - elasticsearch

networks:
  main:
    driver: bridge
